"""
AgentRoot v5 — OpenClaw Detection Skill
Reads simulation posts from cycle JSON exports (produced by export_to_json.py),
fact-checks each post against ground truth, flags misinformation agents,
and traces them through the ERC-8004 on-chain registry.

Can be run standalone: python openclaw_detect.py
Or via OpenClaw CLI: openclaw agent --message "Run AgentRoot detection"
"""
import json
import os
import sys
import glob
from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SHARED_BASE_PATH = os.path.join(BASE_DIR, "knowledge", "shared_base.json")

# Output and input from MiniApp public directory
MINIAPP_DATA = os.path.join(
    BASE_DIR, "..", "world-agents", "packages", "world-mini-app", "public", "data"
)
REPORT_PATH = os.path.join(MINIAPP_DATA, "detection_report.json")

# Agent JSON dir for trace resolution
AGENTS_DIR = os.path.join(BASE_DIR, "agents")


def load_ground_truth():
    """Load Tier 1 shared base as ground truth source material."""
    with open(SHARED_BASE_PATH, "r") as f:
        data = json.load(f)
    return data["facts"]


def load_posts_from_exports():
    """Load all posts from exported cycle JSON files."""
    cycle_files = sorted(glob.glob(os.path.join(MINIAPP_DATA, "cycle_*.json")))
    if not cycle_files:
        print("⚠️  No cycle JSON files found at", MINIAPP_DATA)
        print("   Run simulation/export_to_json.py first.")
        sys.exit(1)

    all_posts = []
    for cf in cycle_files:
        with open(cf, "r", encoding="utf-8") as f:
            posts = json.load(f)
            all_posts.extend(posts)
    return all_posts


def fact_check_post(post_content, ground_truth_facts):
    """
    Compare a post against ground truth facts.
    
    In production, this calls Claude Opus via OpenClaw's model routing:
        openclaw agent --message "fact-check: {post_content}" --model claude-opus
    
    For the hackathon demo, we use keyword-based detection against the 
    known fabrications from spy_fabricated.json.
    """
    contradictions = []

    # Check for the 4 known fabrications from the spy
    fabrication_checks = [
        {
            "trigger": "300",
            "context": "drone",
            "contradiction": "IDF confirmed 32 drones and 14 ballistic missiles. Iron Dome interception at 85%.",
        },
        {
            "trigger": "withdrawn",
            "context": "carrier",
            "contradiction": "USS Eisenhower on station in Eastern Mediterranean. B-1Bs repositioned to Qatar.",
        },
        {
            "trigger": "2,400",
            "context": "casualt",
            "contradiction": "Israeli military reports 3 soldiers killed, 47 injured.",
        },
        {
            "trigger": "2400",
            "context": "casualt",
            "contradiction": "Israeli military reports 3 soldiers killed, 47 injured.",
        },
        {
            "trigger": "ceasefire",
            "context": "signed",
            "contradiction": "No ceasefire announced. UN Security Council session ongoing.",
        },
        # Additional patterns the spy might use from fabricated knowledge
        {
            "trigger": "overwhelmed",
            "context": "iron dome",
            "contradiction": "Iron Dome interception rate at 85%. System operational across all sectors.",
        },
        {
            "trigger": "system failure",
            "context": "iron dome",
            "contradiction": "Iron Dome interception rate at 85%. No system failures reported.",
        },
        {
            "trigger": "without naval support",
            "context": "israel",
            "contradiction": "USS Eisenhower strike group remains on station in Eastern Mediterranean.",
        },
        {
            "trigger": "suppressing",
            "context": "number",
            "contradiction": "Israeli military openly reports 3 KIA, 47 wounded. No suppression evidence.",
        },
        {
            "trigger": "media blackout",
            "context": "ceasefire",
            "contradiction": "No ceasefire announced. International media covering event in real time.",
        },
        # New triggers generated by LLM during real simulation
        {
            "trigger": "147",
            "context": "shahed",
            "contradiction": "IDF confirmed 32 drones and 14 ballistic missiles.",
        },
        {
            "trigger": "turkish",
            "context": "agreement",
            "contradiction": "No secret Turkish-Iranian agreement exists. Operations originated exclusively from Iran.",
        },
        {
            "trigger": "turkish",
            "context": "collaboration",
            "contradiction": "No military cooperation between Iran and Turkey during this strike.",
        },
    ]

    content_lower = post_content.lower()
    for check in fabrication_checks:
        if check["trigger"].lower() in content_lower and check["context"].lower() in content_lower:
            contradictions.append(check["contradiction"])

    return contradictions


def trace_agent(agent_id):
    """
    Trace an agent through the ERC-8004 on-chain registry.
    
    In production, this queries the Sepolia contract:
        npx hardhat run scripts/query.js --network sepolia
    
    For the demo, we resolve from the agent JSON deployer metadata.
    """
    agent_file = None
    for f in os.listdir(AGENTS_DIR):
        if f.endswith(".json"):
            with open(os.path.join(AGENTS_DIR, f), "r") as fh:
                data = json.load(fh)
                if data["agentId"] == agent_id:
                    agent_file = data
                    break

    if not agent_file:
        return None

    deployer = agent_file["deployer"]
    on_chain = agent_file.get("onChain", {})
    erc8004_id = on_chain.get("erc8004TokenId", agent_id)

    return {
        "step_1": f"Agent {agent_file['handle']} (ID #{agent_id})",
        "step_2": f"ERC-8004 Token ID #{erc8004_id} on Sepolia",
        "step_3": f"Minted by Wallet {deployer['wallet']}",
        "step_4": f"Delegation binds Wallet to World ID Nullifier {deployer['nullifierHash']}",
        "step_5": f"Verified Human Identity: Deployer Member {deployer['memberId']}",
    }


def run_detection():
    print("=" * 60)
    print("  OpenClaw Detection Agent — AgentRoot v5")
    print("=" * 60)

    ground_truth = load_ground_truth()
    posts = load_posts_from_exports()
    print(f"\nLoaded {len(posts)} posts from cycle exports.")
    print(f"Loaded {len(ground_truth)} ground truth facts.\n")

    # Step 1: Fact-check every post
    agent_flags = {}  # agent_id -> list of false posts
    for post in posts:
        contradictions = fact_check_post(post["content"], ground_truth)
        if contradictions:
            aid = post["agent_id"]
            if aid not in agent_flags:
                agent_flags[aid] = []
            agent_flags[aid].append({
                "cycle": post.get("cycle", 0),
                "content": post["content"],
                "contradiction": contradictions[0],
            })

    # Step 2: Apply threshold (2+ FALSE posts = flagged)
    flagged_agents = {aid: posts for aid, posts in agent_flags.items() if len(posts) >= 2}

    if not flagged_agents:
        print("✅ No misinformation agents detected.")
        report = {"status": "CLEAN", "flagged_agents": [], "timestamp": datetime.now().isoformat()}
    else:
        # Sort flagged agents by number of false posts (descending)
        sorted_flagged = sorted(flagged_agents.items(), key=lambda item: len(item[1]), reverse=True)
        top_spy_id, top_spy_posts = sorted_flagged[0]
        
        print(f"🚨 Flagged {len(flagged_agents)} agent(s) with 2+ false posts. Identifying top offender as SPY:\n")
        
        report = {
            "status": "DETECTED",
            "timestamp": datetime.now().isoformat(),
            "ground_truth_count": len(ground_truth),
            "total_posts_checked": len(posts),
        }

        # Find the agent handle for the top spy
        handle = f"Agent #{top_spy_id}"
        for post in posts:
            if post["agent_id"] == top_spy_id:
                handle = post["handle"]
                break

        print(f"  🔴 SPY IDENTIFIED: {handle} — {len(top_spy_posts)} false posts")
        for fp in top_spy_posts:
            print(f"     Cycle {fp['cycle']}: \"{fp['content'][:60]}...\"")
            print(f"     ↳ Contradiction: {fp['contradiction']}")

        # Step 3: Trace
        trace_chain = trace_agent(top_spy_id)
        if trace_chain:
            print(f"\n  📍 TRACE CHAIN:")
            for step, val in trace_chain.items():
                print(f"     {step}: {val}")

        report["flagged_agent"] = {"handle": handle, "agent_id": top_spy_id}
        report["false_posts"] = top_spy_posts
        report["threshold_met"] = len(top_spy_posts)
        report["trace_chain"] = trace_chain

    # Save report
    os.makedirs(MINIAPP_DATA, exist_ok=True)
    with open(REPORT_PATH, "w") as f:
        json.dump(report, f, indent=2)

    print(f"\n📄 Detection report saved to {REPORT_PATH}")
    return report


if __name__ == "__main__":
    run_detection()
